# -*- coding: utf-8 -*-
"""[w5-3]9251_LCS.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Un1GdwWCZKoHDsVkARuWHKlg6wGWUk_j
"""

# 1단계: 입력 받기
Alpha = [[0] + list(input()) for i in range(2)]
dp = [[0 for i in range(len(Alpha[1]))] for i in range(len(Alpha[0]))]
result = 0

# 2단계: dp테이블 이용하기
for i in range(len(Alpha[0])):
    for j in range(len(Alpha[1])):
        if i == 0 or j == 0:
            dp[i][j] = 0
        elif Alpha[0][i] == Alpha[1][j]:
            dp[i][j] = dp[i-1][j-1] + 1
        else:
            dp[i][j] = max(dp[i][j-1], dp[i-1][j])

        if result <= dp[i][j]:
            result = dp[i][j]

# 3단계: 결과 출력
print(result)