# -*- coding: utf-8 -*-
"""[w5-5]1463_1로만들기.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GN71MB2uHWU3BPaIvhEPvvKAuzHx07ji
"""

# bottom-up방식
# 1단계: 입력받기
N = int(input())
dp=[0]*(N+1)

# 2단계: dp구하기
for i in range(2,N+1): # 2부터 N까지 반복
    dp[i]=dp[i-1]+1 # 1을 빼는 연산 -> 1회 진행
    if i%2==0: # 2로 나누어 떨어질 때, 2로 나누는 연산
        dp[i]=min(dp[i],dp[i//2]+1)
    if i%3==0: # 3으로 나누어 떨어질 때, 3으로 나누는 연산
        dp[i]=min(dp[i],dp[i//3]+1)


# 3단계: 결과보기
print(dp[N])