# -*- coding: utf-8 -*-
"""[w4]14503_로봇청소기.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1H2n6GVbp8SnRGpRQYPW79SyTbg7SNRVz
"""

# 1단계: 입력받기
N, M = map(int, input().split())
r, c, d = map(int, input().split())
room = [list(map(int, input().split())) for _ in range(N)]

# 2단계: 설정하기
dx = [-1, 0, 1, 0]  # 북동남서(0123)
dy = [0, 1, 0, -1]
cnt = 0

# 3단계: 청소하기
while True:
    # 현재 위치 청소
    if room[r][c] == 0:
        room[r][c] = 2
        cnt += 1

    # 회전 및 이동
    unavail = False
    for _ in range(4):
        nd = (d - 1) % 4  # 왼쪽으로 회전
        nr = r + dx[nd]
        nc = c + dy[nd]
        if 0 <= nr < N and 0 <= nc < M and room[nr][nc] == 0:
            r, c, d = nr, nc, nd
            unavail = True
            break
        else:
            d = nd

    # 네 방향 모두 청소되었거나 벽인 경우
    if not unavail:
        nr, nc = r - dx[d], c - dy[d]  # 후진
        if 0 <= nr < N and 0 <= nc < M and room[nr][nc] != 1:
            r, c = nr, nc
        else:
            break

# 4단계: 결과보기
print(cnt)