# -*- coding: utf-8 -*-
"""[w4]16234_인구이동.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wr1WVX-XsOuK-ruLc-jwftUZa7B812Tz
"""

from collections import deque

# 1단계: 입력받기
N, L, R = map(int, input().split())
box = [list(map(int, input().split())) for i in range(N)]

# 2단계: 설정하기
dx = [-1, 1, 0, 0] #상하좌우순
dy = [0, 0, -1, 1]

# 3단계: 연합국 탐색하기
def bfs(i, j):
    queue = deque()
    union = []
    queue.append((i, j))
    union.append((i, j))

    while queue:
        x, y = queue.popleft()
        for k in range(4):
            nx = x + dx[k]
            ny = y + dy[k]
            if 0 <= nx < N and 0 <= ny < N and visited[nx][ny] == 0:
                if L <= abs(box[nx][ny] - box[x][y]) <= R:
                    visited[nx][ny] = 1
                    queue.append((nx, ny))
                    union.append((nx, ny))
    return union

# 4단계: 인구이동하고 결과 확인하기
result = 0
while True:
    visited = [[0 for _ in range(N)] for _ in range(N)]
    flag = 0
    for i in range(N):
        for j in range(N):
            if visited[i][j] == 0:
                visited[i][j] = 1
                country = bfs(i, j)

                if len(country) > 1:
                    flag = 1
                    people = sum(box[x][y] for x, y in country) // len(country)

                    for x, y in country:
                        box[x][y] = people

    if flag == 0:
        print(result)
        break

    result += 1

2 20 50
50 30
20 40